// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD20oXMlB3vm5jjcn17ZWdoZFIKb2sjXRw',
    appId: '1:32849149020:web:91c58cbd3d4d4f1d8bba99',
    messagingSenderId: '32849149020',
    projectId: 'lawyer-digital-diary',
    authDomain: 'lawyer-digital-diary.firebaseapp.com',
    storageBucket: 'lawyer-digital-diary.appspot.com',
    measurementId: 'G-4GKW0HWCLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcMEI-GtaYe9zyq2iOIsX9rTzXr6uEqo4',
    appId: '1:32849149020:android:889047e982368a028bba99',
    messagingSenderId: '32849149020',
    projectId: 'lawyer-digital-diary',
    storageBucket: 'lawyer-digital-diary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4Pu6pnrG6bOtHWGz8y3XuH0-uhBQXbo',
    appId: '1:32849149020:ios:08862d51d7b540118bba99',
    messagingSenderId: '32849149020',
    projectId: 'lawyer-digital-diary',
    storageBucket: 'lawyer-digital-diary.appspot.com',
    iosBundleId: 'com.example.lawyersDigitalDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD20oXMlB3vm5jjcn17ZWdoZFIKb2sjXRw',
    appId: '1:32849149020:web:28672afa7fb056768bba99',
    messagingSenderId: '32849149020',
    projectId: 'lawyer-digital-diary',
    authDomain: 'lawyer-digital-diary.firebaseapp.com',
    storageBucket: 'lawyer-digital-diary.appspot.com',
    measurementId: 'G-NT4N2MCXYX',
  );
}
